
BCC_BASE_DIR := /opt/lib_install/bcc_llvm
BCCLIBDIR = $(BCC_BASE_DIR)/bcclib/
LLVMPATH = /usr/lib/llvm-12/

LIBBPF_DIR := /opt/lib_install/libbpf_install/

CLANGCC := clang
LLVM_STRIP := llvm-strip
BPFTOOL := $(LIBBPF_DIR)/bin/bpftool

